title: "Connor Sicheri"
description: "My coursework, projects, and blog"
remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme

# Navigation links
header_pages:
  - coursework.md
  - projects.md
  - blog.md
